FROM redhat/ubi8
RUN dnf install wget -y && wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo && rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key&& dnf install java-21-openjdk fontconfig -y && dnf install jenkins -y
WORKDIR /usr/share/jenkins -y
RUN mkdir -p /usr/share/jenkins
RUN wget https://get.jenkins.io/war-stable/latest/jenkins.war
CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
